### ISSUE TITLE
Report progress loading network inputs, building network, and linking points

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#444]
When starting up, a worker does not contact the backend server until these steps are done (see https://github.com/conveyal/r5/blob/dev/src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java).  The front-end will display "initializing cluster" during all of these steps, giving users no sense of whether progress is normal, slower than expected, or stalled due to an error.

Related: #325, #374, #381

**Comment by ansoncfit** [comment]
Addressed in #459 

A commit comment in that PR:
> This still needs to be cleaned up so all different kinds of warnings / errors / wait+retry produce predictable HTTP status codes and response formats (JSON vs. binary, no text/plain).

**Comment by abyrd** [comment]
This issue is partly solved, and the cleanup cited from that PR is also solved. But the progress reporting is not granular enough yet, so I wouldn't consider this issue closed.

**Comment by abyrd** [comment]
Though progress has been made by merging #459, the problem remains that the async loader assumes no eviction of linkages. Once it associates a network with a key, it assumes at all points thereafter that not only the network, but all associated resources like linkages and distance tables are still in cache. 

The way around this is to make the values stored in the async loader compound objects holding references to all needed resources (network, grid, linkage, distance tables) and remove all the other caches, so these are all retained or evicted at once. Then we could apply a cacheWeigher in only one place, in the async loader.

However, we do have evidence that those linkages and tables are not large enough to exhaust our workers' memory in normal use, and were only being evicted because we had the cache size set conservatively to hold only a few linkages. We should experiment with setting this cache size significantly larger or turning it off entirely (no eviction) and see if memory consumption in e.g. Netherlands is reasonable after working on 4-5 scenarios in a row with different access modes.

**Comment by abyrd** [comment]
Via #541 we now have progress reporting on egress cost table building, but still not on network building. The new ProgressListener / Task classes in #541 should facilitate progress reporting during network building.
